### ISSUE TITLE
Suggestion: Make the locale dinamic

### ISSUE THREAD

**Issue by gvsrepins** [JoffreyC22/nova-french-datepicker#1]
Hi @JoffreyC22, thank you for the integration with `flatpickr` 
If you could make it more generic, passing a dinamic `locale` parameter, it will serve in more use cases.

Regards

**Comment by JoffreyC22** [comment]
Hey @gvsrepins ,

This repository will not be maintained anymore since I'm working on something else currently, feel free to fork it and add whatever you need though.

Best regards.
