### ISSUE TITLE
Nullable rule + Placeholder not working

### ISSUE THREAD

**Issue by Coornifex** [JoffreyC22/nova-french-datepicker#2]
Hi @JoffreyC22 ,

I have found some bugs in your Nova Date Package.

When you update a French Date Field with null value, it will keep the old one (if given). I tried with the Nova default Date and it works.

Also, the withMeta Placeholder is not working, Nova 1.3.0 brings the possibility to add Placeholder to dates fields.

Can you fix this bugs please?

Best regards.

**Comment by JoffreyC22** [comment]
Hey @YHamek,

This repository will not be maintained anymore since I'm working on something else currently, feel free to fork it and add whatever you need though.

Best regards.
